### ISSUE TITLE
Add link to all zip files in the tutorial

### ISSUE THREAD

**Issue by luhugerth** [jwdebelius/q2-sidle#11]
The Sequence Reconstruction section states

"Next, you will need to get the tutorial data. You will need to download three sets of files: the sequencing data, the alignments, and the reconstruction files."

But it would be a lot easier to have the wget/unzip commands there also
(forgot to add on my branch, sorry)

**Comment by jwdebelius** [comment]
Thanks for this great suggestion!

**Comment by jwdebelius** [comment]
This got addressed?
