### ISSUE TITLE
Assertion error

### ISSUE THREAD

**Issue by ditag** [jwdebelius/q2-sidle#13]
Hi, 

Thanks for creating sidle! 

However, running the following command I encountered with an issue:

`qiime sidle prepare-extracted-region \`
`--i-sequences  /home/dita.gudra/QIIME2_classifiers/silva-138_5-degen-v12-extracted.qza \`
`--p-region v12 \`
`--p-trim-length 250 \`
`--p-fwd-primer AGAGTTTGATCMTGGCTCAG \`
`--p-rev-primer ACTGCTGCSYCCCGTAGGAGTCT \`
`--o-collapsed-kmers /home/dita.gudra/QIIME2_classifiers/silva_138_v12_kmer_seqs_250.qza \`
`--o-kmer-map /home/dita.gudra/QIIME2_classifiers/silva_138_v12_kmer_map_250.qza \`
`--p-chunk-size 10000 \`
`--p-n-workers 32`

The error that was produced:
`Exception in thread AsyncProcess Dask Worker process (from Nanny) watch process join:`
`Traceback (most recent call last):`
  `File "/home/dita.gudra/miniconda3/envs/qiime2-2020.11/lib/python3.6/threading.py", line 916, in _bootstrap_inner       self.run()`
  `File "/home/dita.gudra/miniconda3/envs/qiime2-2020.11/lib/python3.6/threading.py", line 864, in run self._target(*self._args, **self._kwargs)`
  `File "/home/dita.gudra/miniconda3/envs/qiime2-2020.11/lib/python3.6/site-packages/distributed/process.py", line 235,  in _watch_process assert exitcode is not None`
`AssertionError`

Can you please help out to overcome this?

All the best,
Dita.

**Comment by ditag** [comment]
P.S. The dask version I am using is 2020.12.0

**Comment by jwdebelius** [comment]
Hi @ditag,

I didn't create it, just implmented it. (Hopefully when you're ready to publish, you'll cycle back and cite this as well as the original paper). It's not really ready for prime-time, so it may be buggy and support will eventually move to the qiime2 forum.

As a stop gap, this is an error with the underlying dask system and callbacks. You may want to explore the [dask documentation](https://distributed.dask.org/en/latest/client.html). You could try starting your own client externally, passing it with the `--p-client-address`, which may give you more control. For alignment, I would also use a smaller chunk. I've gotten the best behavior on local systems with about 100 - 250 sequences. This is somewhat dependent on your sequence length.

**Comment by ditag** [comment]
Hi, 

Thanks for the reply.
Might be silly, but I am a bit confused about `--p-client-address`. So let's say, the IP address of a server is `10.1.0.10.` which is protected by a password and has a special port through which to connect (for example `-p 2222`). In that case, I would probably specify something like this:` --p-client-address dita@10.1.0.10:2222`, but I couldn't find any info on how to add a password to dask + tcp. 
Also, I'm running on Debian that is incorporated into a Docker container.

Thank you in advance,
Dita.

**Comment by jwdebelius** [comment]
You need to read the dask documentation and/or look for their development info. If there's an issue with interfacing, I'm happy to take another look, but the client runs based on dask parameters. Otherwise, its hard to provide support for a package that is really still in alpha and _not_ entirely ready to be used.
