### ISSUE TITLE
cannot import name '_dnafastaformats_to_series'

### ISSUE THREAD

**Issue by EdgarsLiepa** [jwdebelius/q2-sidle#16]
After installing q2 sidle-plugin and trying to run qiime `dev refresh-cache` i'm receiving this error: 

```
File "/home/edgars.liepa/miniconda3/envs/qiime2-2021.2/lib/python3.6/site-packages/q2_sidle/_transformer.py", line 11, in <module>

    from q2_types.feature_data._transformer import _dnafastaformats_to_series

ImportError: cannot import name '_dnafastaformats_to_series'

```

I couldn't find `_dnafastaformats_to_series` data type in `q2_types.feature_data._transformer` source code. only `_fastaformats_to_series`

Full error message:

`Traceback (most recent call last): File "/home/edgars.liepa/miniconda3/envs/qiime2-2021.2/bin/qiime", line 11, in <module> sys.exit(qiime()) File "/home/edgars.liepa/miniconda3/envs/qiime2-2021.2/lib/python3.6/site-packages/click/core.py", line 829, in __call__ return self.main(*args, **kwargs) File "/home/edgars.liepa/miniconda3/envs/qiime2-2021.2/lib/python3.6/site-packages/click/core.py", line 782, in main rv = self.invoke(ctx) File "/home/edgars.liepa/miniconda3/envs/qiime2-2021.2/lib/python3.6/site-packages/click/core.py", line 1259, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "/home/edgars.liepa/miniconda3/envs/qiime2-2021.2/lib/python3.6/site-packages/click/core.py", line 1259, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "/home/edgars.liepa/miniconda3/envs/qiime2-2021.2/lib/python3.6/site-packages/click/core.py", line 1066, in invoke return ctx.invoke(self.callback, **ctx.params) File "/home/edgars.liepa/miniconda3/envs/qiime2-2021.2/lib/python3.6/site-packages/click/core.py", line 610, in invoke return callback(*args, **kwargs) File "/home/edgars.liepa/miniconda3/envs/qiime2-2021.2/lib/python3.6/site-packages/q2cli/builtin/dev.py", line 31, in refresh_cache import q2cli.core.cache File "/home/edgars.liepa/miniconda3/envs/qiime2-2021.2/lib/python3.6/site-packages/q2cli/core/cache.py", line 406, in <module> CACHE = DeploymentCache() File "/home/edgars.liepa/miniconda3/envs/qiime2-2021.2/lib/python3.6/site-packages/q2cli/core/cache.py", line 61, in __init__ self._state = self._get_cached_state(refresh=refresh) File "/home/edgars.liepa/miniconda3/envs/qiime2-2021.2/lib/python3.6/site-packages/q2cli/core/cache.py", line 107, in _get_cached_state self._cache_current_state(current_requirements) File "/home/edgars.liepa/miniconda3/envs/qiime2-2021.2/lib/python3.6/site-packages/q2cli/core/cache.py", line 200, in _cache_current_state state = self._get_current_state() File "/home/edgars.liepa/miniconda3/envs/qiime2-2021.2/lib/python3.6/site-packages/q2cli/core/cache.py", line 238, in _get_current_state plugin_manager = qiime2.sdk.PluginManager() File "/home/edgars.liepa/miniconda3/envs/qiime2-2021.2/lib/python3.6/site-packages/qiime2/sdk/plugin_manager.py", line 54, in __new__ self._init(add_plugins=add_plugins) File "/home/edgars.liepa/miniconda3/envs/qiime2-2021.2/lib/python3.6/site-packages/qiime2/sdk/plugin_manager.py", line 81, in _init plugin = entry_point.load() File "/home/edgars.liepa/miniconda3/envs/qiime2-2021.2/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2472, in load return self.resolve() File "/home/edgars.liepa/miniconda3/envs/qiime2-2021.2/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2478, in resolve module = __import__(self.module_name, fromlist=['__name__'], level=0) File "/home/edgars.liepa/miniconda3/envs/qiime2-2021.2/lib/python3.6/site-packages/q2_sidle/plugin_setup.py", line 511, in <module> importlib.import_module('q2_sidle._transformer') File "/home/edgars.liepa/miniconda3/envs/qiime2-2021.2/lib/python3.6/importlib/__init__.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "/home/edgars.liepa/miniconda3/envs/qiime2-2021.2/lib/python3.6/site-packages/q2_sidle/_transformer.py", line 11, in <module> from q2_types.feature_data._transformer import _dnafastaformats_to_series ImportError: cannot import name '_dnafastaformats_to_series'`

**Comment by jwdebelius** [comment]
Hi @EdgarsLiepa,

Either try the qiime2-2020.11 version or the 2021.2-release branch.

**Comment by jwdebelius** [comment]
Hi @EdgarsLiepa,

Have you been able to solve the installation problem with the update?

**Comment by EdgarsLiepa** [comment]
> Hi @EdgarsLiepa,
> 
> Have you been able to solve the installation problem with the update?

Hi @jwdebelius! yes, installation is working fine now with the newest qiime version! Thank you.
