### ISSUE TITLE
Can't extract database file in tutorial

### ISSUE THREAD

**Issue by luhugerth** [jwdebelius/q2-sidle#2]
Running `tar -czf database.tgz` gives the reasonable error "tar: Cowardly refusing to create an empty archive".

However, `tar -xzf database.tgz` gives 
```
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```
which is more problematic...  So what is the file format? I only manage to extract it by using point-and-click, but this doesn't tell me what the format was, or how to extract it in the terminal :neutral_face:

**Comment by jwdebelius** [comment]
I think I solved this with #9 and re-uploaded the files
