### ISSUE TITLE
Memory problems at scale

### ISSUE THREAD

**Issue by jwdebelius** [jwdebelius/q2-sidle#25]
@vitorheidrich raised this issue on the [qiime2 forum](https://forum.qiime2.org/t/q2-sidle-running-out-of-memory-at-reconstruct-counts/19940/15) where the silva database was failing to solve the database due to memory issues.

As a proposed solution, one option is a re-factor to run the command through dask - which may be more memory efficient.  Pros aare thta we are no longer limited by trying to solve the 1M seq dataframe. Potential cons are that it probably means breaking out the database step and will be slower for smaller databases.

**Comment by jwdebelius** [comment]
I think I have a solution. @vitorheidrich, will you try and see if it works for you? It may be easiest to access via Git and then just check out the branch.

https://github.com/jwdebelius/q2-sidle/tree/memory-refactor

If preliminary testing, I was able to reconstruct the Silva database you gave me in like 15 minutes with 4 cores on my macbook with nothing dedicated, so hopefully 🤞 it works. However, this also represents a major refactor, so I updated the docs as well:

https://q2-sidle.readthedocs.io/en/memory-refactor/index.html

There's a fairly good probability of typos in the new docs, but when I ran everything through the tutorial, it worked. (They will need to be updated to fully work, you need to sub the branch name fo the download.)

Give it a whirl and please me know how it works for you.

**Comment by vitorheidrich** [comment]
That's great news! Thank you for looking into this

I'll give it a try later this week and I will let you know how it goes

**Comment by vitorheidrich** [comment]
It worked! With those regional databases + default parameters it took 90min to finish the database reconstruction.

Really cool solution. Once again thank you very much for your efforts with this plugin!

**Comment by jwdebelius** [comment]
Im glad! And 90 min feels reasonable? I think you could increase the cores (default is 1 iirc) but Im not sure I could easily speed up the code by _that_ mucch.

**Comment by vitorheidrich** [comment]
I definitely could use a much higher number of cores, but I just wanted to test if the process would finish (whichever the running time would be), so honestly I am just glad it worked.

**Comment by jwdebelius** [comment]
Closed via #27
