### ISSUE TITLE
Taxonomic databases (Ampliseq pipeline, multiregion sidle option)

### ISSUE THREAD

**Issue by Clasicac** [jwdebelius/q2-sidle#35]
Dear authors, 

I am trying to use (nextflow) ampliseq pipeline ([https://github.com/nf-core/ampliseq ](https://github.com/nf-core/ampliseq/tree/2.11.0)) with the multi region option which use sidle. For the taxonomy step, sidle can use 2 readily databases (silva or GreenGenes2). Unfortunately, those databases have only 16S. I am working with ITS plant, rbcl plant, 12S bird and 12S mammal samples. 

I would like to know if there is other available databases for sidle which could fit with my samples (ITS or Rbcl or 12S) ?
If this doesn't exist, could you advise me on how to make a customized database that works with sidle ?

Thank you in advance for your help!

**Comment by jwdebelius** [comment]
Hi @Clasicac,

I dont provide support like this in issue requests here, please ask on the QIIME 2 forum. (https://forum.qiime2.org/) This is especially true in your case, where I think there may be a solution but it will be easier to find if there's a larger group of developers to consult.

Best,
Justine

**Comment by Clasicac** [comment]
Thx that helps a lot.
